name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  current_time_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print date
        run: |
         date

  current_directory_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print current directory
        run: |
          ls -l